version: "3.9"

services:
  cf-ozeliurs-com:
    image: nginx
    container_name: cf-ozeliurs-com
    restart: unless-stopped
    volumes:
      - ./www:/usr/share/nginx/html:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cf-ozeliurs-com.rule=Host(`cf.ozeliurs.com`)"
      - "traefik.http.routers.cf-ozeliurs-com.entrypoints=websecure"
      - "traefik.http.routers.cf-ozeliurs-com.tls=true"
      - "traefik.http.routers.cf-ozeliurs-com.tls.certresolver=cloudflare"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]

networks:
  traefik:
    external: true